apiVersion: v1
kind: ConfigMap
metadata:
  name: msagw-oauth
data:
  JWKS_HOST: http://192.168.99.1:8080
  JWKS_URI: http://agw:9000/auth-certs
  TOKEN_URI: http://192.168.99.1:8080/auth/realms/msagw/protocol/openid-connect/token
  JWKS_PATH: /auth/realms/msagw/protocol/openid-connect/certs
  AUTHORIZATION_URI: http://192.168.99.1:8080/auth/realms/msagw/protocol/openid-connect/auth
  LOGOUT_URI: http://192.168.99.1:8080/auth/realms/msagw/protocol/openid-connect/logout?redirect_uri=https://k8s.test
  CLIENT_ID: App
  CLIENT_SECRET: f4f76724-2a84-4cd8-83e5-5a5af23a8418
  OAUTH_SCOPE: ""
  NAME_CLAIM: email
  ROLES_CLAIM: roles
