apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app-service: portal
  name: portal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app-service: portal
