---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: portal
  labels:
    app-service: portal
spec:
  selector:
    matchLabels:
      app-service: portal
  replicas: 1
  template:
    metadata:
      labels:
        app-service: portal
    spec:
      containers:
        - name: portal
          image: msagw-portal
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: msagw-oauth
                  key: JWKS_URI
            - name: REACT_APP_AUTH
              value: "true"
