---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: agw
  labels:
    app-service: agw
spec:
  selector:
    matchLabels:
      app-service: agw
  replicas: 1
  template:
    metadata:
      labels:
        app-service: agw
    spec:
      containers:
        - name: agw
          image: msagw-agw
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
            - containerPort: 5701
          env:
            - name: APP_HOST
              value: http://k8s.test
            - name: OAUTH_URI_ROOT
              value: http://192.168.99.1:8080
            - name: JWKS_PATH
              value: /auth/realms/msagw/protocol/openid-connect/certs
            - name: SESSION_TIMEOUT
              value: "1800"
