server:
  port: 9000
spring:
  application:
    name: agw
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: auth-certs
          uri: ${JWKS_HOST}
          predicates:
            - Path=/auth-certs
          filters:
            - RewritePath=/auth-certs, ${JWKS_PATH}
        - id: customers
          uri: http://customers:9001
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers, /
        - id: portal
          uri: http://portal:80
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          iam:
            token-uri: ${TOKEN_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            logout-uri: ${LOGOUT_URI}
        registration:
          iam:
            provider: iam
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_HOST}/login/oauth2/code/iam
            scope: ${OAUTH_SCOPE}
msagw:
  host: ${APP_HOST}
  name-claim: ${NAME_CLAIM}
  roles-claim: ${ROLES_CLAIM}
  session-timeout: ${SESSION_TIMEOUT}
  redis:
    host: redis

