logging:
  level:
    root: INFO
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-certs
          uri: http://localhost:8080
          predicates:
            - Path=/auth-certs
          filters:
            - RewritePath=/auth-certs, /auth/realms/msagw/protocol/openid-connect/certs
        - id: users
          uri: http://localhost:9001
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users, /
        - id: portal
          uri: http://localhost:3000
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          iam:
            token-uri: http://localhost:8080/auth/realms/msagw/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/msagw/protocol/openid-connect/auth
            logout-uri: http://localhost:8080/auth/realms/msagw/protocol/openid-connect/logout?redirect_uri=http://localhost:9000
        registration:
          iam:
            redirect-uri: http://localhost:9000/login/oauth2/code/iam
            client-id: App
            client-secret: f4f76724-2a84-4cd8-83e5-5a5af23a8418
            scope: email,offline_access
msagw:
  name-claim: email
  roles-claim: roles
  host: http://localhost:9000
  session-timeout: 1800
  available-locales: en;en-gb,br;pt-br
  redis:
    host: localhost
