apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app-service: customers
  name: customers
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app-service: customers
