---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: customers
  labels:
    app-service: customers
spec:
  selector:
    matchLabels:
      app-service: customers
  replicas: 1
  template:
    metadata:
      labels:
        app-service: customers
    spec:
      containers:
        - name: customers
          image: msagw-customers
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          env:
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: msagw-oauth
                  key: JWKS_URI
            - name: ROLES_CLAIM
              valueFrom:
                configMapKeyRef:
                  name: msagw-oauth
                  key: ROLES_CLAIM
